add udf
kunpengcompute/omnidata-hive-connector pull request #12
Opened 2022-04-27 08:41 UTC by yang-haitao

add udf file

2022-04-27 10:54 UTC, tedliUCAS commented on connector/src/main/java/org/apache/hadoop/hive/ql/omnidata/config/NdpConf.java
> +        int port = Integer.parseInt(hiveProperties.getProperty(NDP_SDI_PORT, "9105").toLowerCase());
HAF版本已经不需要指定端口号了

2022-04-27 10:54 UTC, tedliUCAS commented on connector/src/main/java/org/apache/hadoop/hive/ql/omnidata/config/NdpConf.java
> +    public Boolean getNdpGrpcSslEnabled() {
本系统不采用grpc通信，不需要这个配置获取

2022-04-27 10:54 UTC, tedliUCAS commented on connector/src/main/java/org/apache/hadoop/hive/ql/omnidata/config/NdpConf.java
> +    public Boolean getNdpGrpcSslEnabled() {
本系统不采用grpc通信，不需要这个配置获取

2022-04-27 10:54 UTC, tedliUCAS commented on connector/src/main/java/org/apache/hadoop/hive/ql/omnidata/config/NdpConf.java
> +    public String getNdpGrpcClientCertFilePath() {
本系统不采用grpc通信，不涉及证书获取

2022-04-27 10:54 UTC, tedliUCAS commented on connector/src/main/java/org/apache/hadoop/hive/ql/omnidata/config/NdpConf.java
> +    public String getNdpGrpcClientCertFilePath() {
本系统不采用grpc通信，不涉及证书获取

2022-04-27 10:54 UTC, tedliUCAS commented on connector/src/main/java/org/apache/hadoop/hive/ql/omnidata/config/NdpConf.java
> +    public String getNdpGrpcClientPrivateKeyFilePath() {
同上，请检查后续配置，存在同样的问题

2022-04-27 10:54 UTC, tedliUCAS commented on connector/src/main/java/org/apache/hadoop/hive/ql/omnidata/config/NdpConf.java
> +    public String getNdpGrpcClientPrivateKeyFilePath() {
同上，请检查后续配置，存在同样的问题

2022-04-27 10:54 UTC, tedliUCAS commented on connector/src/main/java/org/apache/hadoop/hive/ql/omnidata/config/NdpConf.java
> +    public String getNdpZookeeperQuorumServer() {
"agent1:2181"的默认配置并不能保证系统正常运行。

2022-04-27 10:54 UTC, tedliUCAS commented on connector/src/main/java/org/apache/hadoop/hive/ql/omnidata/config/NdpConf.java
> +    public String getNdpZookeeperQuorumServer() {
"agent1:2181"的默认配置并不能保证系统正常运行。

2022-04-27 10:54 UTC, tedliUCAS commented on connector/src/main/java/org/apache/hadoop/hive/ql/omnidata/operator/filter/NdpUdfExpression.java
> +     * name = "upper,ucase"
注释内容描述错误，是lower

2022-04-27 10:54 UTC, tedliUCAS commented on connector/src/main/java/org/apache/hadoop/hive/ql/omnidata/operator/filter/NdpUdfExpression.java
> +     * name = "upper,ucase"
注释内容描述错误，是lower

2022-04-27 10:54 UTC, tedliUCAS commented on connector/src/main/java/org/apache/hadoop/hive/ql/omnidata/operator/filter/NdpUdfExpression.java
> +    private void createNdpGetarrayitem(ExprNodeGenericFuncDesc funcDesc, List<RowExpression> arguments) {
此处开始的private函数的入参，在没有入参校验的情况下做.get(0) .get(1)操作，存在空指针风险。

2022-04-27 10:54 UTC, tedliUCAS commented on connector/src/main/java/org/apache/hadoop/hive/ql/omnidata/operator/filter/NdpUdfExpression.java
> +    private void createNdpGetarrayitem(ExprNodeGenericFuncDesc funcDesc, List<RowExpression> arguments) {
此处开始的private函数的入参，在没有入参校验的情况下做.get(0) .get(1)操作，存在空指针风险。

2022-04-27 10:56 UTC, tedliUCAS commented on connector/src/main/java/org/apache/hadoop/hive/ql/omnidata/config/NdpConf.java
> +        int port = Integer.parseInt(hiveProperties.getProperty(NDP_SDI_PORT, "9105").toLowerCase());
HAF版本已经不需要指定端口号了

2022-04-27 11:15 UTC, xulilililili requested changes

2022-04-27 11:15 UTC, xulilililili commented on connector/src/main/java/org/apache/hadoop/hive/ql/omnidata/config/NdpConf.java
> +                hiveProperties.getProperty(NDP_ZOOKEEPER_RETRY_INTERVAL, "1000").toLowerCase());
retryInterval是int类型，可以不需要.toLowerCase()方法

2022-04-27 11:15 UTC, xulilililili commented on connector/src/main/java/org/apache/hadoop/hive/ql/omnidata/config/NdpConf.java
> +                hiveProperties.getProperty(NDP_ZOOKEEPER_SESSION_TIMEOUT, "60000").toLowerCase());
getNdpZookeeperSessionTimeout(): retryInterval是int类型，可以不需要.toLowerCase()方法

2022-04-27 11:15 UTC, xulilililili commented on connector/src/main/java/org/apache/hadoop/hive/ql/omnidata/config/NdpConf.java
> +                hiveProperties.getProperty(NDP_ZOOKEEPER_CONNECTION_TIMEOUT, "15000").toLowerCase());
getNdpZookeeperConnectionTimeout(): retryInterval是int类型，可以不需要.toLowerCase()方法

2022-04-27 11:15 UTC, xulilililili commented on connector/src/main/java/org/apache/hadoop/hive/ql/omnidata/config/NdpConf.java
> +                hiveProperties.getProperty(NDP_FILTER_SELECTIVITY, "0.5").toLowerCase());
getNdpFilterSelectivity(): selectivity是double类型，可以不需要.toLowerCase()方法

2022-04-27 11:15 UTC, xulilililili commented on connector/src/main/java/org/apache/hadoop/hive/ql/omnidata/config/NdpConf.java
> +        return Integer.parseInt(hiveProperties.getProperty(NDP_TABLE_SIZE_THRESHOLD, "10240").toLowerCase());
getNdpTablesSizeThreshold(): 结果返回是Int类型，可以不需要.toLowerCase()方法

2022-04-27 11:15 UTC, xulilililili commented on connector/src/main/java/org/apache/hadoop/hive/ql/omnidata/config/NdpConf.java
> +        int replicationNum = Integer.parseInt(hiveProperties.getProperty(NDP_REPLICATION_NUM, "3").toLowerCase());
getNdpReplicationNum():replicationNum是int类型。可以不需要toLowerCase

2022-04-27 11:19 UTC, xulilililili commented on connector/src/main/java/org/apache/hadoop/hive/ql/omnidata/config/NdpConf.java
> +        return hiveProperties.getProperty(NDP_ZOOKEEPER_CONF_PATH, "/opt/hadoopclient/ZooKeeper/zookeeper/conf/");
建议默认的zookeeper的配置路径设置为：/usr/local/zookeeper/conf

2022-04-28 01:34 UTC, Jutao-liu commented on connector/src/main/java/org/apache/hadoop/hive/ql/omnidata/config/NdpConf.java
> +
该版本为haf版本，不依赖grpc，建议删除

2022-04-28 01:42 UTC, Jutao-liu commented on connector/src/main/java/org/apache/hadoop/hive/ql/omnidata/config/NdpConf.java
> +    public final String NDP_GRPC_SSL_ENABLED = "hive.sql.ndp.grpc.ssl.enabled";
该版本为不依赖grpc，建议删除

2022-04-28 01:45 UTC, yang-haitao commented on connector/src/main/java/org/apache/hadoop/hive/ql/omnidata/config/NdpConf.java
> +    public final String NDP_GRPC_SSL_ENABLED = "hive.sql.ndp.grpc.ssl.enabled";
已删除grpc参数

2022-04-28 01:45 UTC, yang-haitao commented on connector/src/main/java/org/apache/hadoop/hive/ql/omnidata/config/NdpConf.java
> +
已删除grpc参数

2022-04-28 01:45 UTC, yang-haitao commented on connector/src/main/java/org/apache/hadoop/hive/ql/omnidata/config/NdpConf.java
> +        return hiveProperties.getProperty(NDP_ZOOKEEPER_CONF_PATH, "/opt/hadoopclient/ZooKeeper/zookeeper/conf/");
将配置路径修改为/usr/local/zookeeper/conf

2022-04-28 01:46 UTC, yang-haitao commented on connector/src/main/java/org/apache/hadoop/hive/ql/omnidata/config/NdpConf.java
> +        int replicationNum = Integer.parseInt(hiveProperties.getProperty(NDP_REPLICATION_NUM, "3").toLowerCase());
删除toLowerCase方法

2022-04-28 01:46 UTC, yang-haitao commented on connector/src/main/java/org/apache/hadoop/hive/ql/omnidata/config/NdpConf.java
> +        return Integer.parseInt(hiveProperties.getProperty(NDP_TABLE_SIZE_THRESHOLD, "10240").toLowerCase());
删除toLowerCase方法

2022-04-28 01:46 UTC, yang-haitao commented on connector/src/main/java/org/apache/hadoop/hive/ql/omnidata/config/NdpConf.java
> +                hiveProperties.getProperty(NDP_FILTER_SELECTIVITY, "0.5").toLowerCase());
删除toLowerCase方法

2022-04-28 01:46 UTC, yang-haitao commented on connector/src/main/java/org/apache/hadoop/hive/ql/omnidata/config/NdpConf.java
> +                hiveProperties.getProperty(NDP_ZOOKEEPER_CONNECTION_TIMEOUT, "15000").toLowerCase());
删除toLowerCase方法

2022-04-28 01:46 UTC, yang-haitao commented on connector/src/main/java/org/apache/hadoop/hive/ql/omnidata/config/NdpConf.java
> +                hiveProperties.getProperty(NDP_ZOOKEEPER_SESSION_TIMEOUT, "60000").toLowerCase());
删除toLowerCase方法

2022-04-28 01:47 UTC, yang-haitao commented on connector/src/main/java/org/apache/hadoop/hive/ql/omnidata/config/NdpConf.java
> +                hiveProperties.getProperty(NDP_ZOOKEEPER_RETRY_INTERVAL, "1000").toLowerCase());
删除toLowerCase方法

2022-04-28 01:48 UTC, yang-haitao commented on connector/src/main/java/org/apache/hadoop/hive/ql/omnidata/operator/filter/NdpUdfExpression.java
> +    private void createNdpGetarrayitem(ExprNodeGenericFuncDesc funcDesc, List<RowExpression> arguments) {
该方法进入前已做校验

2022-04-28 01:48 UTC, yang-haitao commented on connector/src/main/java/org/apache/hadoop/hive/ql/omnidata/operator/filter/NdpUdfExpression.java
> +     * name = "upper,ucase"
描述修改为lower

2022-04-28 01:49 UTC, yang-haitao commented on connector/src/main/java/org/apache/hadoop/hive/ql/omnidata/config/NdpConf.java
> +    public String getNdpZookeeperQuorumServer() {
默认配置修改为localhost

2022-04-28 01:49 UTC, yang-haitao commented on connector/src/main/java/org/apache/hadoop/hive/ql/omnidata/config/NdpConf.java
> +    public String getNdpGrpcClientPrivateKeyFilePath() {
已删除grpc配置

2022-04-28 01:49 UTC, yang-haitao commented on connector/src/main/java/org/apache/hadoop/hive/ql/omnidata/config/NdpConf.java
> +    public String getNdpGrpcClientCertFilePath() {
已删除grpc配置

2022-04-28 01:50 UTC, yang-haitao commented on connector/src/main/java/org/apache/hadoop/hive/ql/omnidata/config/NdpConf.java
> +    public Boolean getNdpGrpcSslEnabled() {
已删除grpc配置

2022-04-28 01:50 UTC, yang-haitao commented on connector/src/main/java/org/apache/hadoop/hive/ql/omnidata/config/NdpConf.java
> +        int port = Integer.parseInt(hiveProperties.getProperty(NDP_SDI_PORT, "9105").toLowerCase());
已删除grpc配置

2022-04-28 01:51 UTC, merged